version: "3.9"

services:
  api:
    build: .
    container_name: finance_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://192.168.1.123:3000
    ports:
      - "8989:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - finance-bridge

networks:
  finance-bridge:
    external: true